### ISSUE TITLE
Bottom sheet snap too high causing back layout exposed at bottom

### ISSUE THREAD

**Issue by fadhlisulaimi** [osdnk/react-native-reanimated-bottom-sheet#106]
I'm not sure if I am doing this correctly, but my bottom sheet is always snapped too high when opened, resulting in the bottom part being exposed to my main layout. Is it because of safeareaview? I tried changing snapPoints[0] to a fixed number, adjusting the height, adding margins to renderInner View but it doesn't work.

```
renderInner = () => (
          <View style = {{
              backgroundColor: '#fff000',
              height: '100%',
          }}>
              <Text>Copy</Text>
          </View>
      )

<SafeAreaView>
<MyMainContent />
 <BottomSheet
                    ref={this.bs}
                    snapPoints = {['100%', '0%']}
                    initialSnap={1}
                    renderContent = {this.renderInner}
                />
</SafeAreaView>
```

![IMG_0287](https://user-images.githubusercontent.com/12539080/66717659-fb52bd80-ee0d-11e9-87cb-69c72748d306.gif)

**Comment by romanonthego** [comment]
You could "solve" problem for now by just setting `overdragResistanceFactor` to `0`  :)
It's not ideal, but will solve an issue.

**Comment by jona-ng** [comment]
I had the same problem. I worked around by setting the bottom position to 0 (in line with the bottom of the screen) and setting the closed snap point to the amount I wanted the bottom sheet to be visible. Having bottom or marginBottom to offset the sheet causes this issue.

**Comment by asharafshahi** [comment]
I also had this problem when the top most container View had padding.  When I removed the padding (even just paddingTop), the bottomSheet aligned with the bottom of the screen.

**Comment by mnjongerius** [comment]
I solved this by placing the `BottomSheet` outside of the  `SafeAreaView`

**Comment by maguayo** [comment]
As @mnjongerius said, placing the BottomSheet outside of the SafeAreaView solves the problem

**Comment by dmcchanaka** [comment]
Please use your bottom sheet outside of SafeAreaView

**Before recorrect**
<img src="https://user-images.githubusercontent.com/38916928/183027324-0cf31c34-03e7-42c1-853e-ce3e19db6cd9.png" data-canonical-src="https://user-images.githubusercontent.com/38916928/183027324-0cf31c34-03e7-42c1-853e-ce3e19db6cd9.png" width="200" height="400" />

**After recorrect**
<img src="https://user-images.githubusercontent.com/38916928/183027384-5cc80c66-2584-4dcc-916a-872dcd4e4653.png" data-canonical-src="https://user-images.githubusercontent.com/38916928/183027384-5cc80c66-2584-4dcc-916a-872dcd4e4653.png" width="200" height="400" />

Use your code like this

`<View style={{flex:1}}>`
    `<SafeAreaView style={styles.container}>`
         `......rest of codes`
   ` </SafeAreaView>`
    `<BottomSheet />`
`</View>`
