### ISSUE TITLE
onPress function on Android not working 

### ISSUE THREAD

**Issue by funkyyy** [osdnk/react-native-reanimated-bottom-sheet#107]
Hey guys if want to add a onPress function to open a link 
its not working on Android.

On iOS it works very well.
I dont know how to fix this :/

this is my code
`
<ListItem>
                <TouchableOpacity
                  style={styles.infoScreenOpenMaps}
                  onPress={() => {
                    Linking.openURL(
                      "https://maps.google.com/?q=" + lati + "," + longi
                    );
                  }}
                >
                  <Icon
                    style={styles.markerIcon}
                    name="map-marker-outline"
                    type="material-community"
                    color='#8a8a8a'
                  />
                  <Text>In Google Maps öffnen</Text>
                </TouchableOpacity>
</ListItem>`

**Comment by robertototti** [comment]
try to add this attribute `enabledContentTapInteraction={false}`

**Comment by imdanielpiva** [comment]
Hi, @funkyyy did it work?

**Comment by lander854** [comment]
Worked for me

**Comment by mayconmesquita** [comment]
@robertototti tip worked for me

**Comment by micheilsgrey** [comment]
BTW, i tried to use `TouchableOpacity`  `onPress` from `react-native `and in Android it wasn't working but if i improt from `react-native-gesture-handler` it worked but stopped working in iOS :) real strange behavior, `enabledContentTapInteraction={false}` fixes this issue for both ios and android with `TouchableOpacity` from `react-native`.

**Comment by funkyyy** [comment]
> Hi, @funkyyy did it work?

yes it worked! thanks

**Comment by adlme** [comment]
> try to add this attribute `enabledContentTapInteraction={false}`

You da best!!!!

**Comment by ffchn** [comment]
> try to add this attribute `enabledContentTapInteraction={false}`

Oh my god, you're the best! This thing was driving me crazy!
