### ISSUE TITLE
Accessibility on bottom sheet.

### ISSUE THREAD

**Issue by i-sbaral** [osdnk/react-native-reanimated-bottom-sheet#124]
Hi guys , this is more of a question than an issue.

I am making an react native app which supports accessibility ( Three finger swipe when voice-over is turned on , etc, etc) . Is there a way to make the bottom sheet accessible ?  Any suggestions would be highly appreciated.

**Comment by BloodyBeans** [comment]
You could wrap the header in a TouchableOpacity/TouchableHiglight and toggle the open and close when onPress. Hope this helped you

**Comment by i-sbaral** [comment]
@BloodyBeans. Thank you for your suggestion. Turns out IOS way of dragging the bottom sheet it to double tap and hold the item until it is selected . Then , it can be dragged as necessary when voice over is running.
