### ISSUE TITLE
The instructions is not clear

### ISSUE THREAD

**Issue by boypanjaitan16** [osdnk/react-native-reanimated-bottom-sheet#137]
I tried the provided example and nothing happen, can you be more clear about how to use this lib ?

**Comment by blohamen** [comment]
@boypanjaitan16 , can you please watch https://github.com/osdnk/react-native-reanimated-bottom-sheet/blob/master/Example/Map.js#L44 . I think it can be helpful for you. And if you want more examples you can watch this section https://github.com/osdnk/react-native-reanimated-bottom-sheet#example
