### ISSUE TITLE
Invariant Voilation: Text strings must be rendered within a <Text> component 

### ISSUE THREAD

**Issue by SaimAhmedSheikh** [osdnk/react-native-reanimated-bottom-sheet#141]
I' ve got this error after installling the library and using BottomSheet in my app:

`Invariant Voilation: Text strings must be rendered within a <Text> component`

**Comment by joeyfigaro** [comment]
@SaimAhmedSheikh your text has to be wrapped within a `Text` component:

```js
import { Text, View } from 'react-native'

const MyComponent = () => (
  <View>
    <Text>Your text here</Text>
  </View>
)
```

**Comment by BrtqKr** [comment]
@SaimAhmedSheikh not sure if you solved this, but I remember having the same issue. It was caused by spaces {' '} in some parts of the code. Removing them manually seems to help. It could have been caused by setting up the whole thing incorrectly.
