### ISSUE TITLE
how to make swipe threshold smaller

### ISSUE THREAD

**Issue by ospfranco** [osdnk/react-native-reanimated-bottom-sheet#146]
I have 3 snapPoints, the highest one being the screen height, this causes a problem however, when you try to swipe up, you really have to drag your finger really high in the screen to make the bottom sheet snap, I tried changing the value of `callbackThreshold` but it doesn't seem to affect how far you need to drag the sheet.

Any suggestions on how to solve this?

**Comment by harterc1** [comment]
I need help with this too.   My snap points are a fairly far distance apart and a "flick" gesture is more natural than a "drag".   It'd be nice if we could define a swipe velocity threshold or something that would make the bottomsheet snap to the next snap point if the users gesture was quick enough.

**Comment by ospfranco** [comment]
I don't think the library is unmaintained, but it seems @osdnk is not on top of the issues, maybe the best course would be to create a PR, right now I'm in the middle of a major refactoring, but I will try to create a PR early next year.

**Comment by lauridskern** [comment]
having the same issue would be nice having such an option!

**Comment by zmnv** [comment]
need the same prop

**Comment by zmnv** [comment]
I found that `bouncyFactor` provides sensitivity of change snapped position. 

https://github.com/osdnk/react-native-reanimated-bottom-sheet/blob/master/src/index.tsx#L138

```
const magic = {
  ...
  bouncyFactor: 1
}
```

I set it to `0.05` for tests, try yourself.

**Comment by ospfranco** [comment]
@zmnv I tried playing around with the magic variables as well, but none of them seem to affect the swiping threshold, the type information says they might control only the animation, on the other hand, this piece of code:

```typescript
for (let i = 1; i < snapPoints.length; i++) {
      middlesOfSnapPoints.push(
        divide(add(snapPoints[i - 1], snapPoints[i]), 2),
      );
    }```

seems to calculate where are the transitions points are, after I changed the divider from 2 to 1.3, the transitions points are lower, which effectively solves the action when swiping up, when swiping down however it means it also is lower which is again kinda shitty,you can use patch-package to change this logic yourself and adjust it for your needs.

It would be great if someone can take some time and share the patch-package here and create PR at the same time, having the middle of the snaps as a range rather than a single point seems reasonable to me, unfortunately I don't have the time to take care of this right now.

**Comment by ospfranco** [comment]
I managed to get it working with our use case, the PR is open but I don't know if it will ever be merged, you can however patch package the library yourselves, just take a look at my PR, you will need to modify the compiled JS files though, sorry I cannot do anything more for you atm.

**Comment by zmnv** [comment]
@ospfranco thank you very much for trying help!
I can use .tsx file directly instead of compiling to .js. Will try!

One question. Where the `threshold` value?

Is it:
```
const tuple = [add(snapPoints[i - 1], 10), snapPoints[i]]
```

Is `10` as second argument in `add(x1, x2)` is a `threshold`?

in https://github.com/osdnk/react-native-reanimated-bottom-sheet/pull/163/files#diff-38682f47b0cf12c516bc3714fc45d0fdR344

**Comment by ospfranco** [comment]
Yes, you can .add or .sub to change the thresholds

**Comment by harterc1** [comment]
I think the swipe threshold we're talking about should be configurable via a prop.

And it might be more intuitive to have it be `velocityThreshold={500}` so that regardless of position between snap points, if the velocity of the swipe exceeds +/-500, it snaps in the direction of the swipe.

**Comment by ospfranco** [comment]
logic is fairly convoluted because you don't really have access to the current position, everything is node via reanimated nodes, so just trying to rely on speed is not possible in the current implementation.

PRs are not being merged anyways, this library is dead on the water, so it doesn't really matter, but you can try to patch it yourself.

**Comment by lucbas** [comment]
Thanks @ospfranco for your work!
A pity that this won‘t be continued.

**Comment by zmnv** [comment]
Hi guys. 

Without `<-this` touchable elements in header will open bottom sheet by `onPress`.

```
        for (let i = 1; i < snapPoints.length; i++) {
            const tuple: [Animated.Node<number>, Animated.Node<number>] = [
                add(snapPoints[i - 1], 10),
                sub(snapPoints[i], 25),    # <-this
            ]
            middlesOfSnapPoints.push(tuple)
        }

```

**Comment by zmnv** [comment]
@ospfranco ALARM MAN!

Why did you set up `let i = 1`? Because of that it works only after first try..
I setup it to `0` and now it works by first time.

Please check it. Look case videos in imgur:
https://imgur.com/a/wqDjYJV

```
        for (let i = 0; i < snapPoints.length; i++) {
            const tuple: [Animated.Node<number>, Animated.Node<number>] = [
                add(snapPoints[i - 1], 10),
                sub(snapPoints[i], 10),
            ]
            middlesOfSnapPoints.push(tuple)
        }
```

**Comment by ospfranco** [comment]
it has been quite some time since I submitted this PR, as far as I remember the calculation logic works from the top, so having i start at 0 doesn't make since because you are calculating the mid points *between* the snap points (`snapPoints[i-1]`) when I tested it was working just fine, maybe it has something to do with the initial snapPoint when you mount your component? 

In any case, I don't think I'll submit any PR, I no longer work at the company where I was using this component, so feel free to patch it, but as far as I can tell, setting it to 0 should cause a index out of bound access to the snap point array
