### ISSUE TITLE
Customize the speed of animation

### ISSUE THREAD

**Issue by ShuKTan** [osdnk/react-native-reanimated-bottom-sheet#154]
Hi,

First of all, thank you for this great library.

Everything is working smooth till now with this library. Just want to slow down the sliding up and sliding down animation of bottom sheet. 

How can I change it?

**Comment by harterc1** [comment]
Try using the `springConfig` prop.  I'm pretty sure you can use this for reference to help you out: https://software-mansion.github.io/react-native-reanimated/spring-utils.html
