### ISSUE TITLE
Current snap point

### ISSUE THREAD

**Issue by andywu0408** [osdnk/react-native-reanimated-bottom-sheet#157]
Thanks for this wonderful library. It would be great if we can determine which snap point index we're at currently. Thanks!

**Comment by BCarroll524** [comment]
You can try the following to do this.

```javascript
const Example = () => {
const [callbackNode, setCallbackNode] = useState<Animated.Value<number>>(
    new Animated.Value(0),
  )

doSomething = () => {
  const currentValue = (callbackNode as any)._value
    if (currentValue === 0) {
      bs.current.snapTo(1)
      setCallbackNode(new Animated.Value(1))
    } else {
      bs.current.snapTo(0)
      setCallbackNode(new Animated.Value(0))
    }

const bs = React.createRef<BottomSheet>()

  return (
    <BottomSheet
      ref={bs}
      snapPoints={[0, 400]}
      renderHeader={renderHeader}
      renderContent={renderInner}
      initialSnap={0}
      callbackNode={callbackNode}
    />
  )
}
```

**Comment by ChronSyn** [comment]
> You can try the following to do this.
> 
> ```js
> const Example = () => {
> const [callbackNode, setCallbackNode] = useState<Animated.Value<number>>(
>     new Animated.Value(0),
>   )
> 
> doSomething = () => {
>   const currentValue = (callbackNode as any)._value
>     if (currentValue === 0) {
>       bs.current.snapTo(1)
>       setCallbackNode(new Animated.Value(1))
>     } else {
>       bs.current.snapTo(0)
>       setCallbackNode(new Animated.Value(0))
>     }
> 
> const bs = React.createRef<BottomSheet>()
> 
>   return (
>     <BottomSheet
>       ref={bs}
>       snapPoints={[0, 400]}
>       renderHeader={renderHeader}
>       renderContent={renderInner}
>       initialSnap={0}
>       callbackNode={callbackNode}
>     />
>   )
> }
> ```

Unfortunately, when trying this, the result is the snap to is triggered, but then it is reset to its previous position - e.g. currently in position 0 --- [ TAP EVENT ] ---> animates to position 1 ---> animates to position 0
