### ISSUE TITLE
Expo SDK 35 Support

### ISSUE THREAD

**Issue by Jwb81** [osdnk/react-native-reanimated-bottom-sheet#158]
I've tried to install this package using Expo 35, but it throws an error saying 'Unable to resolve module `react-native-reanimated` from `....../node_modules/reanimated-bottom-sheet/lib/module/index.js`: Module `react-native-reanimated` does not exist in the Hate module map.

I cloned the example app and it works perfect, so I am thinking it is an Expo version/compatibility issue.

**Comment by osdnk** [comment]
You need to add reanimated with `expo install react-native-reanimated`

**Comment by minhthien309** [comment]
I was installed react-native-reanimated but got `Unable to resolve "./core/Animation Function" from "node_modules\react-native-reanimated\src\base.js"` (I'm using Expo 35 too)
