### ISSUE TITLE
Text selectable not working inside renderContent

### ISSUE THREAD

**Issue by baijii** [osdnk/react-native-reanimated-bottom-sheet#160]
As I try to select Text within the content, it won't work. There is only a copy callout but no native selection handles. It would be really great if someone finds the source of it.

```
<BottomSheet
    renderContent={() => (
        <Text selectable>Hello World</Text>
    )}
/>
```

happened on iOS, iPhone 8, current version 1.0.0-alpha.18

**Comment by BrtqKr** [comment]
It looks more like a RN issue in general and it seems to happen on ios only. The only workaround I managed to find was a solution suggested here: [Click and hold to select text using a text component #13938](https://github.com/facebook/react-native/issues/13938#issuecomment-520590673)
