### ISSUE TITLE
Gesture doesn't work on android

### ISSUE THREAD

**Issue by yasir-netlinks** [osdnk/react-native-reanimated-bottom-sheet#167]
I can't seem to be able to get it to work, I copied the examples for testing, `Example/Map.js` and others but I can't seem to be able to drag the modal, this is happening only on `android`, `iOS` works fine. any suggestions, thank you
Also, could you please add support for typescript

![Screen Shot 2020-02-01 at 09 24 57](https://user-images.githubusercontent.com/26054956/73587130-00c73700-44d5-11ea-88f6-6a113f088577.png)

I'm wondering if the above error is what causing the problem for `android` to not work

### Test Device that has the problem
* Galaxy S9+ (Android 9)

### Environment
* reanimated-bottom-sheet: ^1.0.0-alpha.18
* React Native: 0.61.5
* react-native-reanimated: ^1.4.0
* react-native-gesture-handler: ^1.5.2
```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
    }
```

**Comment by yasir-netlinks** [comment]
Sorry, it seems that I've forgot to configure `gesture-handler` properly
https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/127#issuecomment-555397385

**Comment by azhararmar** [comment]
For me it worked when I updated my the `index.js` file of the project with following

```
import 'react-native-gesture-handler';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
```
