### ISSUE TITLE
Get snap position

### ISSUE THREAD

**Issue by vforvasile** [osdnk/react-native-reanimated-bottom-sheet#173]
How to get your current snap position by using this.bs.current....

When you manually interact with the bottomsheet using gestures you're not aware of the current snapping position. 

Did anyone manage to find a workaround?

**Comment by windht** [comment]
Hi there is indeed a way to get the current drawerCallback node's position like the following. Where `onCallback` is where you get the value and use to perform animation or anything else.

```
import Animated from 'react-native-reanimated';

const {
  call,
  onChange
} = Animated;

class Drawer extends Component {

drawerCallbackNode = new Animated.Value(0);

onCallback = ([value]) => {
    this.setState({
      openRatio: 1 - value // this is something varies from 0-1
    });
};


render () {
// Somewhere in render
<BottomSheet
  snapPoints={[..]}
  initialSnap={1}
  callbackNode={this.drawerCallbackNode}
/>

<Animated.Code
  exec={onChange(
    this.drawerCallbackNode,
    call([this.drawerCallbackNode], this.onCallback))}
/>
}

}
```

**Comment by vforvasile** [comment]
thanks @windht, I decided to switch to [react-native-modalize](https://github.com/jeremybarbet/react-native-modalize) as it covers my requirements.

**Comment by arshkkk** [comment]
> Hi there is indeed a way to get the current drawerCallback node's position like the following. Where `onCallback` is where you get the value and use to perform animation or anything else. But yeah it is a value from 0 to 1 so you need to calculate the actual position accordingly.
> 
> ```
> import Animated from 'react-native-reanimated';
> 
> const {
>   call,
>   onChange
> } = Animated;
> 
> class Drawer extends Component {
> 
> drawerCallbackNode = new Animated.Value(0);
> 
> onCallback = ([value]) => {
>     this.setState({
>       openRatio: 1 - value // this is something varies from 0-1
>     });
> };
> 
> 
> render () {
> // Somewhere in render
> <BottomSheet
>   snapPoints={[..]}
>   initialSnap={1}
>   callbackNode={this.drawerCallbackNode}
> />
> 
> <Animated.Code
>   exec={onChange(
>     this.drawerCallbackNode,
>     call([this.drawerCallbackNode], this.onCallback))}
> />
> }
> 
> }
> ```

Doesn't this causes a lot of re-renders of component, like we are putting the something in the Render method which will trigger state updates
