### ISSUE TITLE
Ignore overdragResistanceFactor if enabledInnerScrolling is true

### ISSUE THREAD

**Issue by brentvatne** [osdnk/react-native-reanimated-bottom-sheet#18]
This value should always be zero when the sheet content is scrollable, because overdrag in this scenario should just lead to scrolling. See attached gif for what can sometimes happen if this is set with `enabledInnerScrolling`.

![oopsie](https://user-images.githubusercontent.com/90494/54893314-5fae2f80-4e72-11e9-8974-84cc44363bf9.gif)

**Comment by osdnk** [comment]
Fixed, love max
