### ISSUE TITLE
Unable to pass callbackNode in react native reanimated-bottom-sheet react-native node module

### ISSUE THREAD

**Issue by dkabx** [osdnk/react-native-reanimated-bottom-sheet#204]
`const fall = new Animated.Value(1)
<BottomSheet
snapPoints={[820, 150]}
callbackNode={fall}
initialSnap={1}
renderHeader={() => (
  <View>
    <Text>HEADER</Text>
  </View>
)}
renderContent={() => <Content />}
/>`
When i pass callbackNode as fall which is new Animated.Value(1) getting error

Invariant Violation Reanimated: Animated.set first argument should be of type  AnimatedNode but got [object object]

**Comment by txvnt** [comment]
How did you solve this problem?

**Comment by martppa** [comment]
@dkabx Have you solved the issue? Please share your solution.

**Comment by dkabx** [comment]
I followed @martppa, It worked for me @txvnt .
Thanks @martppa
