### ISSUE TITLE
Update the expo SDK for example 

### ISSUE THREAD

**Issue by saihaj** [osdnk/react-native-reanimated-bottom-sheet#210]
Can you update the Expo SDK for the example (demo app) on Expo and also in the repo?
<img width="952" alt="image" src="https://user-images.githubusercontent.com/44710980/79160936-41c6ac00-7da0-11ea-9ad4-3629b5ce168b.png">

**Comment by neiker** [comment]
Yep, 0.33 is no longer supported

<img width="382" alt="imagen" src="https://user-images.githubusercontent.com/688444/80099308-a1f9e280-8544-11ea-8c97-db171113dcb0.png">

**Comment by neiker** [comment]
https://github.com/osdnk/react-native-reanimated-bottom-sheet/pull/215

**Comment by osdnk** [comment]
fixed :)
