### ISSUE TITLE
snapTo method only works good if called two times

### ISSUE THREAD

**Issue by lukebars** [osdnk/react-native-reanimated-bottom-sheet#211]
Hey! I'm currently having some issues with `snapTo` method.

If I call it to present the bottom sheet like this
```jsx
// Present bottom sheet on button press
const onButtonPress = () => {
    bottomSheetRef.current.snapTo(1)
}

// Hide bottom sheet on inner button press
const onInnerButtonPress = () => {
    bottomSheetRef.current.snapTo(0)
}

// sheet setup
<View>
    <Button onPress={onButtonPress} />
    <BottomSheet
        snapPoints = {[0, 250]}
        renderContent = {this.renderContent} // inner button lies here
    />
</View>
```

So this works only if I press both buttons twice or call `snapTo` twice in each function.. 

However `snapTo` works when i hide the sheet with gesture.

Looks like you can't use method multiple times in a row without gesture interaction. 
By the way, waiting time between presses doesn't change anything

**Comment by amilaDulanjana** [comment]
i am also having this issue
@lukebars Did you able to solve this or any workaround?

**Comment by lukebars** [comment]
@amilaDulanjana Currently I'm resorting to double calling the method.. dirty, but works.

**Comment by SocialBrothersDEV** [comment]
Same here

**Comment by osdnk** [comment]
should be fixed on master

**Comment by Aryk** [comment]
You also I think resolved another issue where "hide" was also opening other bottom sheets.   👏
