### ISSUE TITLE
Change default percent of scrolling(50%) to switch to next snap point

### ISSUE THREAD

**Issue by Kladislav** [osdnk/react-native-reanimated-bottom-sheet#220]
I need less than 50% scroll the bottom sheet to switch him to next snap point. Help pls)

**Comment by zybkinel** [comment]
I have same problem.
I find in lib code:
`node_modules/reanimated-bottom-sheet/src/index.tsx:350`
```
for (let i = 1; i < snapPoints.length; i++) {
      middlesOfSnapPoints.push(divide(add(snapPoints[i - 1], snapPoints[i]), 2))
}
```
From this follows the intermediate point is always 50% of the distance between the points.
In my case, I just changed the divisor.

**Comment by zybkinel** [comment]
I have same problem.
I find solution - `toss` field in `springConfig` attr:
```
<BottomSheet
    springConfig={{
        toss: 10,
    }}
     ...
    />
```

**Comment by Kladislav** [comment]
Thanks =)

**Comment by Filetes97** [comment]
Hi @zybkinel , can you explain what this "toss" prop does?

**Comment by zybkinel** [comment]
Hi @Filetes97, I found a better solution: https://jeremybarbet.github.io/react-native-modalize/#/

**Comment by Filetes97** [comment]
@zybkinel ahah funny. I started the transition to that lib too. 
It looks better for the solution I need :)
