### ISSUE TITLE
Keyboard push BottomSheet to top (TextInput)

### ISSUE THREAD

**Issue by mleister97** [osdnk/react-native-reanimated-bottom-sheet#221]
Hey,

First, thank you! The Bottomsheet is really cool and I really like it.
I created 2 TextInputs inside the Bottomsheet. When I open the Keyboard the BottomSheet is pushed to the top. Any ideas how I can fix this? I couldn't find any solution and already tried wrapping with Scrollview / KeyBoardAvoidingView

Bottomsheet with Inputs:
![WhatsApp Image 2020-05-03 at 14 10 34](https://user-images.githubusercontent.com/16700053/80914521-5b7a6400-8d4c-11ea-891c-9f9f16add762.jpeg)

When pressing inside a TextInput:
![WhatsApp Image 2020-05-03 at 14 10 34 (1)](https://user-images.githubusercontent.com/16700053/80914525-5ddcbe00-8d4c-11ea-872a-3d3038256ec7.jpeg)

Thank you so much for your help!

**Comment by oferRounds** [comment]
Hey @mleister97 did you find any solution to this? Seeing it as well

**Comment by mleister97** [comment]
@oferRounds Unfortunately not.
There are many solutions like wrapping it with a KeyboardAvoidingView, replacing all `flex:1` with `height:100%`, or using `android:windowSoftInputMode="adjustPan"` in Androidmanifest.xml.

As I am using expo and I cannot escape, the last solution is not an option for me. Also @ljmocic mentioned, that just resnapping should also work.
Sadly non of the solutions work for me. I would still be very happy if someone can provida an example.

You can also have a look at this one: #203 
Please notify me when you found a working solution!

**Comment by oferRounds** [comment]
@mleister97 thank you for this detailed answer! I’ll have a look on the other issue, and will keep you posted if find any solution! Thank you again!

**Comment by mleister97** [comment]
Any solution found?

**Comment by karimcambridge** [comment]
Duplicate of #203

**Comment by mleister97** [comment]
You are right, but have you found any solution?

**Comment by karimcambridge** [comment]
Use heights instead of flex fixes it for me. Do not swap the bottom sheet in scrollviews either

**Comment by mleister97** [comment]
Please share an example, i can't fix this

**Comment by karimcambridge** [comment]
In your code, you have your bottom sheet in a parent view right

You have to use height there too and in the render content

**Comment by mleister97** [comment]
I already tried that. Did not work for me. You can also checkout the duplicate, there I posted my code. Maybe you can help me.

I will close this as its a duplicate of #203

**Comment by yzalvov** [comment]
Setting the device screen height to the `BottomSheet`'s parent container worked for me. I posted an example code in the referred thread [#203](https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/203#issuecomment-633950872)
