### ISSUE TITLE
Flatlist inside the BS isn't scrollable on android

### ISSUE THREAD

**Issue by praneeth-hiver** [osdnk/react-native-reanimated-bottom-sheet#224]
Not able to make both the BottomSheet and the Flatlist respond to scroll gesture on android

**Comment by Xadinsx** [comment]
import flatlist from 'react-native-gesture-handler' 

it worked for me :)

**Comment by praneeth-hiver** [comment]
@Xadinsx Worked just fine, Thanks!

**Comment by yasir-netlinks** [comment]
@Xadinsx @praneeth-hiver hi there, I am having problem with not being able to scroll up all item in the list
```
renderContent = () => (
    <View
      style={{
        height: 600,
        backgroundColor: 'green',
        marginHorizontal: '5%',
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        padding: moderateScale(10),
      }}>
      <ScrollView>
        {arr.map((i: any) => {
          return (
            <View style={{height: 50, backgroundColor: 'yellow'}}>
              <Text>{i}</Text>
            </View>
          );
        })}
      </ScrollView>
    </View>
  );
```
what shall I do, I have been stuck on this for a while now

**Comment by PatrissolJuns** [comment]
> import flatlist from 'react-native-gesture-handler'
> 
> it worked for me :)

Thanks a lot!

**Comment by mzu** [comment]
> import flatlist from 'react-native-gesture-handler'

Should be 
```import { FlatList } from 'react-native-gesture-handler';```

afaik
