### ISSUE TITLE
[Suggestion Needed] Question regarding implemenation in certain use cases.

### ISSUE THREAD

**Issue by roshangm1** [osdnk/react-native-reanimated-bottom-sheet#23]
How would you implement this library in the following use case ? 
I have a bottom tab navigator with 4 tabs. I have to show bottom sheet with different content in different tabs (even 1 tab can have different content).

One approach would be to have the bottom sheet in the root file and calling it from other tab. (Problem here would be rendering dynamic height and dynamic content for bottom sheet for each tab (as height and content are not consistent).

Other approach would be to have bottom sheet for each tab. With this approach, in `snapPoints=[0, 400]`, `snapPoints[0]` is not going to be true 0 from the bottom of app screen. It's going to be the `bottom: 0` from tab navigator instead.

I am not thinking of calculating height of the tab navigator and making `snapPoints=[-heightOfTabNavigator, 400]` or similar. Suggest me if this is a good idea. 

I am using https://www.npmjs.com/package/react-native-tab-navigator [This is a pretty old project 🗡 ] for tab navigator. But I am willing to use react-navigation's bottom navigator if required. 

Any kind of suggestions would be helpful. :) 

cc @brentvatne @osdnk @Eyesonly88 @satya164  (Sorry to mention you guys here ) 🥂

**Comment by Eyesonly88** [comment]
I'd use react-navigation and have a bottomSheet for each tab so you won't have to worry about calculating the height and bottom 0 would not overlap with the bottom tab bar. You can also use react-navigation SafaArea component to control the boundaries for notch phones.

**Comment by roshangm1** [comment]
@Eyesonly88 With this approach, how would you give the `initialSnap` or `snapPoints` for Bottom sheet in each tab ? Giving 0 (position from bottom) would actually result in position from the navigation bar, right ? I haven't tried this yet but I was kind of hoping this will be the expected behavior. 
However, I will give it a shot.

**Comment by roshangm1** [comment]
Seems like, the issue I was mentioning doesn't occur with react-navigation's BottomNavigator. But yeah, the bottom navigator hides certain portion of the bottom sheet. Let me do a bit of more work on this. Thanks @Eyesonly88 for the reply.

**Comment by brentvatne** [comment]
it sounds like react-native-tab-navigator uses absolute positioning with padding, so when things are absolute positioned inside of it, it goes below the padding. you could fork it to not be absolute positioned and that'd probably fix your problem, or use react-navigation bottom tab, or use react-navigation-tabs directly
