### ISSUE TITLE
How to programmaticaly close a BottomSheet after open it ?

### ISSUE THREAD

**Issue by PatrissolJuns** [osdnk/react-native-reanimated-bottom-sheet#242]
First, Thanks for this awesome library. However, I'm a little bit stuck about something. I'm currently showing the bottom sheet on press on something then inside it, I have something a close button which I want it to close the bottom sheet. So please how can I achieve it?

**Comment by nicoache1** [comment]
@PatrissolJuns The snapPoints are the "position" of the bottomSheet at the moment. For example if you have `snapPoints={[0, 200]}`:

- To open the bottom sheet is going to the snap point in position 1 -> `bottomSheetRef.current.toSnap(1)`
- So to close the bottom sheet is to return to the first snap point who is in the position 0 -> `bottomSheetRef.current.toSnap(0)`

**Comment by PatrissolJuns** [comment]
Thanks. It worked!
