### ISSUE TITLE
Strange space at the bottom when headerMode='none' with React Navigation

### ISSUE THREAD

**Issue by Janak-Nirmal** [osdnk/react-native-reanimated-bottom-sheet#247]
Facing strange empty transparent space at the bottom when headerMode is set to 'none'. This screenshot is from the Example => Test.js file 

I have tried setting height to 100% to the Animated.View used for renderContent
Can you point please me in right direction, what should I configure ?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-22 at 09 02 45](https://user-images.githubusercontent.com/1412113/85246138-6eb1d200-b467-11ea-8c8a-6c8cda60e363.png)

**Comment by blixit** [comment]
I got the same issue. I noticed that it happens when the content rendered from renderHeader() has a fixed height and when the height of this content is not enough to cover the unexpected space. Please confirm or not my hypothesis.

**Comment by blixit** [comment]
I got the same issue this morning.

It's not a full and complete solution, but in my case I fixed a part of the problem by putting the BottomSheet outside the SafeAreaView. The other part was related to the dimensions of the header and the footer of my page.

**Comment by Janak-Nirmal** [comment]
@blixit Thank you. Moving this outside the SafeArea It worked, like you said. Thanks as lot.

**Comment by speter9701** [comment]
I had a similar problem. There was a huge empty space blocked (around half of the screen if the bottom sheet is opened to full screen).
The structure was like this:
<View style={{ flex: 1 }}>
  <View>
    <BottomSheet/>
    <View (with the background's content) />
  <View>
<View> 

I solved this problem by removing one <View> layer:

<View style={{ flex: 1 }}>
  <BottomSheet/>
    <View (with the background's content) />
<View>

The removed view layer did not had any styles or settings so I honestly don't know why it was breaking the sheet. Hope it will help someone in the future.
