### ISSUE TITLE
Bottom sheet content not clickable on android

### ISSUE THREAD

**Issue by gawrysiak** [osdnk/react-native-reanimated-bottom-sheet#25]
Created a snack: https://snack.expo.io/SkCT567t4

On android, the content elements of bottom sheet don't execute "onPress" when clicked. For some reason it still launches the ripple effect. It's all okay on iOS. Another thing is it works on long press.

Versions: alpha 3-8

Any ideas?

**Comment by roshangm1** [comment]
This issue has been already discussed in #16 . You have to use Touchables from `react-native-gesture-handler` as a workaround. Follow the related issue for more detail

**Comment by HAFDIAHMED** [comment]
> react-native-gesture-handler

@roshangm1  you are not right , i got the same issue but i solve by importing touchables from react-native direclty not  r`eact-native-gesture-handler`
when you import them from` react-native-gesture-handler`  they didt work
