### ISSUE TITLE
Scroll View or Flat List not scrolling to the end of items

### ISSUE THREAD

**Issue by henoktsegaye** [osdnk/react-native-reanimated-bottom-sheet#274]
I have a Flat list implementation that is imported from **react-native-gesture-handle** 

but when I start to scroll all elements are not showing here is the code

**I tried making the content body height 100% and flexGrow:1 , but seems not to solve the issue**

The behavior seems to appear whether I am using Scrollview or Flatlist

const LONG_DATA = [...]

```
 <BottomSheet`
      bottomSheerColor="white"
      initialPosition={200}  //200, 300
      snapPoints={snapPoints}
      isBackDrop={false}
      overdragResistanceFactor={0}
      isRoundBorderWithTipHeader={true}
      initialSnap={1}
       enabledInnerScrolling={true}
      enabledInnerScrolling
      enabledContentTapInteraction={false}
      header={
        <View>
          <Text category="h6" style={{ textAlign: 'center' }} > Header </Text>
        </View>
      }
      body={
       <Flatlist 
style={{height:'100%',}}
data={LONG_DATA}
renderItem={renderItem}
/>

      }/>
```

**Comment by Stringsaeed** [comment]
@henoktsegaye i think this is only android issue can you confirm if it happens on ios, if it only android issue you can paddingBottom by the height of android's bottom view you can use this library https://github.com/Sunhat/react-native-extra-dimensions-android

**Comment by henoktsegaye** [comment]
Yes its an android issue

**Comment by vorasudh** [comment]
@Stringsaeed , Adding paddingBottom is not solving the issue. You still can not scroll down the list on Android.
@osdnk Any ideas or workaround?

**Comment by Stringsaeed** [comment]
@vorasudh `paddingBottom` in `contentContainerStyle` not in `style` prop, I'm sure that's working,
the workaround is just that you need to add some space after scrolling area so you can use padding or margin or even an empty `View` saving that space to be overlapped by Android's bottom navigation bar

**Comment by henoktsegaye** [comment]
it is still causing an issue just switched to another package

**Comment by faysal515** [comment]
> it is still causing an issue just switched to another package

@henoktsegaye Which package are you using now?
