### ISSUE TITLE
Is there a way to limit the bottom sheet highest stop position? 

### ISSUE THREAD

**Issue by xiaohai0520** [osdnk/react-native-reanimated-bottom-sheet#287]
if I don't want the bottom sheet can pull up to the top of the screen, what can I do? Thanks.

**Comment by speter9701** [comment]
Set only one height in snapLocation.

In the constructor:
this.state = { snapLocation: [150], snapIndex: 0 }

In the render:
<BottomSheet snapPoints={this.state.snapLocation} initialSnap={this.state.snapIndex} {...} />

If you want to pull it up but stop before the top of the screen:

this.state = { snapLocation: [(Dimensions.get('window').height - 150),150], snapIndex: 0 }
