### ISSUE TITLE
Render content issue on android

### ISSUE THREAD

**Issue by laneboyandrew** [osdnk/react-native-reanimated-bottom-sheet#302]
Hello. Today i faced problem testing BottomSheet on android emulator.  I created renderInner:

`<View style={styles.panel}>
                    <Text style={styles.panelTitle}>{currentMarker.title}</Text>
                    <Text style={styles.panelSubtitle}>{currentMarker.description}</Text>
                    <View style={{
                        marginBottom: 10,
                        marginLeft: -15,
                    }}>
                    <SliderBox
                        images={currentMarker.images}
                        useScrollView
                        sliderBoxHeight={400}
                        onCurrentImagePressed={index => console.warn(`image ${index} pressed`)}
                        dotColor="#FFEE58"
                        inactiveDotColor="#90A4AE"
                        autoplay
                        dotStyle={{
                            width: 15,
                            height: 15,
                            borderRadius: 15,
                            marginHorizontal: 10,
                            padding: 0,
                            margin: 0,
                        }}
                        resizeMode={'contain'}
                        ImageComponentStyle={{borderRadius: 15, width: '100%'}}
                        underlayColor="transparent"
                        imageLoadingColor='black'
                    />

                    </View>
                    <View style={{marginTop: 10}}>
                        <Text> <Icon name='map-marker'/>{currentMarker.coordinate.latitude}, {currentMarker.coordinate.longitude}</Text>
                    </View>
                    <View style={{marginTop: 10}}>
                        <StarRating ratings={currentMarker.rating} reviews={currentMarker.reviews}/>
                    </View>
                    <View style={styles.button}>
                        <TouchableOpacity
                            onPress={() => {
                                navigation.navigate('DetailsScreen', {currentMarker: currentMarker})
                            }}
                            style={[styles.signIn, {
                                borderColor: '#FF6347',
                                borderWidth: 1
                            }]}
                        >
                            <Text style={[styles.textSign, {
                                color: '#FF6347'
                            }]}>Подробнее</Text>
                        </TouchableOpacity>
                    </View>
                </View>`

Then i pasted it to BottomSheet param renderContent: 
`
<BottomSheet ref={bs}
                         snapPoints={[500, 250, 0]}
                         borderRadius={10}
                         renderContent={renderInner}
                         initialSnap={2}
            />
`

The problem is I can't scroll through the images and TouchableOpacity doesn't work either. If i use my renderInner like JSX without BottomSheet it works as expected and this problem only occurs on android, on iphone it works fine. 
For clarity, I'll give a link to the screen shot. (https://imgur.com/a/G5i8GBo) Any ideas?

**Comment by ChristianDigitalPlankton** [comment]
I had the same issue with being unable to scroll on android. I fixed it by setting the enabledContentGestureInteraction prop to false. That disables you from dragging the content down to dismiss the BottomSheet, but being able to scroll and interact with the content. You'll have to use the header to drag down the BottomSheet.

**Comment by laneboyandrew** [comment]
> I had the same issue with being unable to scroll on android. I fixed it by setting the enabledContentGestureInteraction prop to false. That disables you from dragging the content down to dismiss the BottomSheet, but being able to scroll and interact with the content. You'll have to use the header to drag down the BottomSheet.

Thank you so much for reply. This solution works. Could you please give me example with header, I really need to drag the BottomSheet down.

**Comment by ChristianDigitalPlankton** [comment]
The header can be anything, just set the renderHeader prop exactly as you set the renderContent. If it's a view with height 50 and width 100%, it will have gesture interaction to drag down the bottomsheet.

**Comment by laneboyandrew** [comment]
> The header can be anything, just set the renderHeader prop exactly as you set the renderContent. If it's a view with height 50 and width 100%, it will have gesture interaction to drag down the bottomsheet.

Thanks, I think that's the best solution that i found.
