### ISSUE TITLE
snap height issue

### ISSUE THREAD

**Issue by ansarikhurshid786** [osdnk/react-native-reanimated-bottom-sheet#321]
I have setup following: 
```
import { Dimensions } from "react-native";

const HEIGHT = Dimensions.get("window").height;
const bottomSheetSnapPoint = [HEIGHT - 130, 250, 0];

<BottomSheet
                            enabledContentGestureInteraction={false}
                            ref={(ref) => { this.bottomSheetRef = ref; }}
                            snapPoints={bottomSheetSnapPoint}
                            initialSnap={2}
                            renderHeader={this.BottomDrawerHeader}
                            renderContent={this.BottomDrawerContent}
                            onOpenEnd={() => { this.setState({ bottomDrawerState: 2 }) }}
                            onCloseStart={() => { this.setState({ bottomDrawerState: 1 }) }}
                            onCloseEnd={() => { this.commonReset() }}
                            style={{ zIndex: 1 }}
                        />

```

How to manage height in iphone x, 11 and 12?

**Comment by cozmoc** [comment]
You can fix it using something like this:

`import { useSafeAreaFrame } from 'react-native-safe-area-context';`

and in your component:
`const { height: DEVICE_HEIGHT } = useSafeAreaFrame();`
`  snapPoints={[
        DEVICE_HEIGHT - 130,
        250,
        0
    ]}
`

make sure you have this wrapper in your `App.tsx`:
`
import { SafeAreaProvider, initialWindowMetrics } from 'react-native-safe-area-context';
<SafeAreaProvider initialMetrics={initialWindowMetrics}>
   ...
</SafeAreaProvider>
`

**Comment by ansarikhurshid786** [comment]
thanks. I have update react native version from 0.59.10 to 0.63.4. Now working fine perfectly.
