### ISSUE TITLE
BottomSheet is hiding but doesn't close

### ISSUE THREAD

**Issue by luqiborges** [osdnk/react-native-reanimated-bottom-sheet#349]
When I press the top of the bottomsheet and drag him down, for closing, bottomsheet get out of the screen but still open, blocking the screen until I press on the screen, closing the bottom sheet. Can anybody help?

**Comment by suhaillilac** [comment]
try this patche by @yzalvov  https://gist.github.com/yzalvov/28133b3654ddb2724b201902937608cd

**Comment by yzalvov** [comment]
👀
