### ISSUE TITLE
BottomSheet  import from react-native-reanimated-bottom-sheet is not available in RN 0.69.1

### ISSUE THREAD

**Issue by Stwax** [osdnk/react-native-reanimated-bottom-sheet#387]
Package is no longer working. BottomSheet can't be imported in a RN 0.69.1 project because, unfortunately, there is no longer a BottomSheet default export. Any help in fixing this will be highly appreciated.

**Comment by DuduSorbet** [comment]
look at this:
https://github.com/software-mansion/react-native-reanimated/issues/3305#issuecomment-1164050099

and then at this:
https://github.com/software-mansion/react-native-reanimated/issues/3246#issuecomment-1140310763

worth a try, worked for me with https://github.com/gorhom/react-native-bottom-sheet
