### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by iits-reza** [osdnk/react-native-reanimated-bottom-sheet#398]
I am using the basic example of bottom-sheet but I got this error:
Cannot read property 'prototype' of undefined 

    "reanimated-bottom-sheet": "^1.0.0-alpha.22"
________________________________________________________
    "react-native": "0.72.4",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-paper": "^5.10.4",
    "react-native-reanimated": "^3.5.4",

**Comment by Frontend-dev-sarah** [comment]
I got the same error after updatint to the latest version of expo 49.

**Comment by iits-reza** [comment]
> I got the same error after updatint to the latest version of expo 49.

I don't use expo workflow but I think the issue is going to be the same! I can't use even other bottom sheet libraries! :/

**Comment by Frontend-dev-sarah** [comment]
> > I got the same error after updatint to the latest version of expo 49.
> 
> I don't use expo workflow but I think the issue is going to be the same! I can't use even other bottom sheet libraries! :/

Yes, the issue is the same, expo 49 using RN 0.72.4. This morning I finally solved this problem by using another bottom lib: https://gorhom.github.io/react-native-bottom-sheet.

**Comment by iits-reza** [comment]
I am not that lucky, I have tried this before and even didn't get a solution 🫠,
But thanks anyway

**Comment by huhu1030** [comment]
> > > I got the same error after updatint to the latest version of expo 49.
> > 
> > 
> > I don't use expo workflow but I think the issue is going to be the same! I can't use even other bottom sheet libraries! :/
> 
> Yes, the issue is the same, expo 49 using RN 0.72.4. This morning I finally solved this problem by using another bottom lib: https://gorhom.github.io/react-native-bottom-sheet.

Documentation says compatible with Reanimated  V1 and V2, did It work with V3 ? @Frontend-dev-sarah

**Comment by ankitjpk2023** [comment]
Any further update on this topic!

**Comment by Frontend-dev-sarah** [comment]
> > > > I got the same error after updatint to the latest version of expo 49.
> > > 
> > > 
> > > I don't use expo workflow but I think the issue is going to be the same! I can't use even other bottom sheet libraries! :/
> > 
> > 
> > Yes, the issue is the same, expo 49 using RN 0.72.4. This morning I finally solved this problem by using another bottom lib: https://gorhom.github.io/react-native-bottom-sheet.
> 
> Documentation says compatible with Reanimated V1 and V2, did It work with V3 ? @Frontend-dev-sarah

My projet uses V3, yes it works with V3.

**Comment by ankitjpk2023** [comment]
@rezamohdev 
How did you mange to solve this!

**Comment by iits-reza** [comment]
> @rezamohdev How did you mange to solve this!

I did not solve it yet and left my project did you solve it?

**Comment by demfabris** [comment]
is this being maintained?

**Comment by sonnt2510** [comment]
@demfabris sadly i believe is not

**Comment by lukasz-szulborski** [comment]
Same problem here after moving to reanimated 3.x and Expo 49. I think it's time to move on and try another library...

**Comment by OzgunOzdemir** [comment]
Has anyone solved this problem ? Is the only solution to use another package ?

**Comment by huhu1030** [comment]
> Has anyone solved this problem ? Is the only solution to use another package ?

As mentioned by @Frontend-dev-sarah, you can use **react-native-bottom-sheet** it works with Expo 49 and Reanimated V3. Even though the documentation does not mention Reanimated V3.

**Comment by JaburBr** [comment]
Same error after moving to expo 49, has anyone else managed to solve this?

**Comment by JaburBr** [comment]
> Same error after moving to expo 49, has anyone else managed to solve this?

I've tried, but the only solution was migrate to 
https://www.npmjs.com/package/@gorhom/bottom-sheet

It worked fine with Expo 49 and Reanimated V3

**Comment by kilejiunderscorea** [comment]
What is going on please, I can't even run the example code because of this error

**Comment by compwron** [comment]
I am also unable to run the example code, I also get this error. Screenshot: 
<img width="434" alt="Screenshot 2024-08-08 at 7 48 43 AM" src="https://github.com/user-attachments/assets/27fda8c1-72e0-46d0-96b4-7ad2cdd8ffd7">

**Comment by Xx-Parks-xX** [comment]
Same error, I just use the basic example but it doesn't work (cannot read property 'prototype' of undefined).
I use expo 51.0.28 and reanimated 3.10.1

**Comment by rezamohdev** [comment]
Hey guys I am going to close this issue, because there is no solution and it seems the library is not supported and developed any more .
thanks everyone !

**Comment by iits-reza** [comment]
Hey guys I am going to close this issue, because there is no solution and it seems the library is not supported and developed any more .
thanks everyone !
