### ISSUE TITLE
[Suggestion needed] How to pass callbackNode animated value to a parent component

### ISSUE THREAD

**Issue by cedricavigo** [osdnk/react-native-reanimated-bottom-sheet#42]
I am trying to achieve some interaction when the bottom sheet is hidden and visible. I am able to follow the example and I have added the animated value to a view within the same component(add opacity & remove). 

Now, I would like to animate a component which is not part of this based on the callbackNode value. This could be a basic approach, but I am new to RN and any advise to achieve this experience will be great.

**More details:**

App.js

```
<SafeAreaView style={styles.container} forceInset={{ bottom: 0 }}>
        <View style={styles.notifHolder}>
          <NotifPanel /> <----- A notification panel(based on react-native-reanimated example) is always visible(25%). FYI, this is an Interactable.View.
        </View>
        <Nav /> <----- Bottom sheet code is inside a stack navigation page
</SafeAreaView>
```

**Expected output/effect:**

I would like to,
a) Slowly hide the notifications panel based on the callbackNode snap position to 1
b) Same way, I would like to bring the notifications panel back when the callbackNode snap position is 0

Thanks for your help!

**Comment by cedricavigo** [comment]
@roshangm1 - Any quick advise on this scenario, like how you helped on my other question :)

**Comment by satya164** [comment]
You need to lift the property up in the tree so you can pass it to the components which use it. The concept is very similar to https://reactjs.org/docs/lifting-state-up.html

**Comment by cedricavigo** [comment]
@satya164 - Will try this.
