### ISSUE TITLE
How to implement callback based on the contentPosition prop ?

### ISSUE THREAD

**Issue by itsyogesh** [osdnk/react-native-reanimated-bottom-sheet#54]
Thanks a lot for this library. I am trying to work on a pull to refresh UI ( I already have flat list rendered in the bottom sheet content). I know there are three gesture handlers that get passed through the instance, but I am not sure how to go about it. 

I am thinking of getting the initial position of the header ref and check if the drag went below a certain level ( say maybe -50) and then trigger it. What I am not able to find is how do I get the initial position of the header ref and how to keep a check on where the header ref current is.

P.S. I couldn't find a StackOverflow tag for this so had to ask here. Let me know if there is anything you aren't clear about. I would try my best to come up with an example.

**Edit**
After going through the examples I figured out that you need to get the **contentPosition** from the prop and based on the value you can define a custom callback. What I am not quite sure about is where do I  implement the callback. I saw the callbackNode prop but it only accepts an animatedValue which gets updated based on the content position.

**Comment by BrtqKr** [comment]
Thank you for your work. Since headerPosition prop was added there haven't been any activity, so I guess this issue can now be closed.
