### ISSUE TITLE
TypeError: Cannot read property 'val' of undefined

### ISSUE THREAD

**Issue by pianoman730** [osdnk/react-native-reanimated-bottom-sheet#56]
This error is located at BottomSheetBehavior at Map.js:16

Steps to reproduce:

I have a simple app that has a bottom tab bar navigation. From just trying to get this going, it doesn't show up at all if I remove everything except the snap points, which are listed as required to render. If I include the initialSnap prop in any way, it throws the error in the title. A `Map.js` file is one of the screens:
```js
import React from 'react';
import { View, StyleSheet } from 'react-native';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';
import BottomSheet from 'reanimated-bottom-sheet';
import renderMarker from './Marker';

const Map = () => {
  return (
    <View style={{ ...StyleSheet.absoluteFillObject }}>
      <BottomSheet
        snapPoints={[500, 250]}
        renderContent={() => <View />}
        initialSnap={250} //this line gives the error described
      />
      <MapView
        provider={PROVIDER_GOOGLE}
        showsUserLocation
        showsMyLocationButton
        followUserLocation
        showsCompass
        style={{ ...StyleSheet.absoluteFillObject }}
        initialRegion={initialRegion}
      >
        {renderMarker()}
      </MapView>
    </View >
  );
};

export default Map;
```

**Comment by blohamen** [comment]
Initial snap - determines initial snap point of bottom sheet. The value is the **INDEX** from snapPoints.
Try this: 
initialSnap={1}

**Comment by pianoman730** [comment]
@blohamen that's what I did have at first, pulling from the doc. The 250 was me messing around trying to get it to work. No dice.

**Comment by satya164** [comment]
Can you provide a repro on snack?

**Comment by pianoman730** [comment]
@satya164 I haven't been able to get MapView working on snack at all. I also haven't been able to get the bottom sheet to work in general on snack. Not sure if the sdk is happy with it. I can try and get a repo spun up to run what I have in an ejected app.

**Comment by pianoman730** [comment]
Are there certain compatibility issues that I could try and look at?

**Comment by pianoman730** [comment]
I tried making a new project with it and saw that my gesture-handler package was out of date. Updated and good to go!
