### ISSUE TITLE
Bottom sheet move too high when keyboard appears

### ISSUE THREAD

**Issue by Pholenk** [osdnk/react-native-reanimated-bottom-sheet#63]
I found a weird behavior when I put text input in the bottom sheet. My snap point is only 0 and device's width but when text input focused and keyboard appears, bottom sheet slide to the top of screen. The problem is; I have a header which floats above all components. So I can not see text input when I type something.

**Comment by iamolegga** [comment]
Try to wrap everything in https://facebook.github.io/react-native/docs/keyboardavoidingview

**Comment by Pholenk** [comment]
thanks for the answer. it's working for me

**Comment by lauridskern** [comment]
@Pholenk what exactly did you wrap? I just can't get it to work. My bottom sheet wont move and I cant see the text input.

**Comment by Pholenk** [comment]
> @Pholenk what exactly did you wrap? I just can't get it to work. My bottom sheet wont move and I cant see the text input.

i just wrapped all the view that contains the text input so it'll looks like:
```JS
<KeyboardAvoidingView>
  <View>
    <TextInput />
  </View>
</KeyboardAvoidingView>
```
you can insert behaviour props of KeyboardAvoidingView as it explained in the official documentation.

**Comment by williamgurzoni** [comment]
I'm using this https://github.com/APSL/react-native-keyboard-aware-scroll-view
It solves all problems.
