### ISSUE TITLE
Reference react-native-gesture-handler documentation for android in readme

### ISSUE THREAD

**Issue by wizebin** [osdnk/react-native-reanimated-bottom-sheet#70]
If you're setting up `react-native-gesture-handler` for the first time you must override the root view in your `MainActivity.java` file, for anyone using this library without already having setup `react-native-gesture-handler` this library appears incorrectly to be broken on android.

We should add in a caveat to follow [the gesture handler getting started guide](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html) instead of simply saying "install and link" when installing the peer dependencies.

**Comment by irwwwan** [comment]
You save my day dude :D
