### ISSUE TITLE
Disable enabledGestureInteraction only for content

### ISSUE THREAD

**Issue by franjorub** [osdnk/react-native-reanimated-bottom-sheet#74]
I want to use this library https://www.npmjs.com/package/react-native-scrollable-tab-view inside the BottomSheet but it only works if enabledGestureInteraction is false, but I need keep the drag feature to move the BottomSheet, what can I do ?

**Comment by ankitsehgal94** [comment]
@franjorub 
Did you find any solution for the react-native-scrollable-tab-view. When i am trying to click the tabs . Its not responding in android.  Working fine in ios.
Thanks

**Comment by franjorub** [comment]
@ankitsehgal94 take a look to #78
