### ISSUE TITLE
react natvie 0.60 no sliding up/down

### ISSUE THREAD

**Issue by Asif77** [osdnk/react-native-reanimated-bottom-sheet#75]
Hi dear,

I am using it in 0.60. i put enabledGestureInteraction true. but i am not able sliding up/donw. any help. thanks,

**Comment by Asif77** [comment]
it is working nwo after change in mainactivity java..

**Comment by koo27** [comment]
> it is working now after changing in mainactivity java..

@Asif77  What exactly did you do to make it work?
