### ISSUE TITLE
Modal bug

### ISSUE THREAD

**Issue by songxiaoliang** [osdnk/react-native-reanimated-bottom-sheet#77]
When I put the bottomsheet into Modal, iOS can slide normally, Android can't slide。
 `<Modal>
     <>
        <Animated.Code
          exec={onChange(
            this.clampedDrawerCallbackNode,
            block([
              cond(
                greaterOrEq(this.clampedDrawerCallbackNode, 1),
                call([], () => {
                  console.log(`[${new Date()}] Drawer closed`)
                })
              ),
              cond(
                lessOrEq(this.drawerCallbackNode, 0),
                call([], () => {
                  console.log(`[${new Date()}] Drawer opened`)
                })
              ),
            ])
          )}
        />
        <BottomSheet
          callbackNode={this.drawerCallbackNode}
          renderContent={() => <Content />}
          renderHeader={() => <Header />}
          snapPoints={[230, 0]}
        />
     </>
</Modal>`

**Comment by songxiaoliang** [comment]
When I put the bottomsheet into Modal, iOS can slide normally, Android can't slide。

**Comment by dsznajder** [comment]
@songxiaoliang Unfortunately it's not related to `reanimated-bottom-sheet` but directly to `react-native-gesture-handler` 
https://github.com/kmagiera/react-native-gesture-handler/issues/139

**Comment by RichardLindhout** [comment]
I use the portal from react-native-paper
import { Portal } from 'react-native-paper'
Instead of a modal. The modalhost is in the root of the application so you don't need a modal to show it outside relative components.

**Comment by songxiaoliang** [comment]
@RichardLindhout Portal Can not achieve the effect of coverscreen

**Comment by RichardLindhout** [comment]
@songxiaoliang Can you take a screenshot, I don't understand what you mean.

**Comment by hayyaun** [comment]
Same problem here... The only solution I found was to add a stack in RootStack above TabNav...
Or toggle TabBarVisbile method of react-navigation

**Comment by RichardLindhout** [comment]
Check this out: https://github.com/osdnk/react-native-slack-bottom-sheet/

**Comment by RichardLindhout** [comment]
@hayyaun @songxiaoliang https://github.com/osdnk/react-native-slack-bottom-sheet/

**Comment by sergeymild** [comment]
Swipe gestures on BottomSheet as a Modal on android still not working

**Comment by lhagva98** [comment]
> Swipe gestures on BottomSheet as a Modal on android still not working

and me
