### ISSUE TITLE
Request to Add Product in Start React

### ISSUE THREAD

**Issue by maheshwari-1153** [osdnk/react-native-reanimated-bottom-sheet#79]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start React](https://startreact.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. 

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by osdnk** [comment]
Hey, let's do it. I'll ad the license!

Many thanks!

**Comment by maheshwari-1153** [comment]
thanks
