### ISSUE TITLE
What is the required version of react native for this ? Not working on 0.58.4

### ISSUE THREAD

**Issue by roshangm1** [osdnk/react-native-reanimated-bottom-sheet#8]
What is the required version of react native for this ? 
This is the screen i am seeing on Android. 

![image](https://user-images.githubusercontent.com/5866078/54774142-22a82a00-4c33-11e9-8ddd-1260f3d08f5e.png)

**Comment by roshangm1** [comment]
I just found out, state -> heightOfHeader doesn't have the initial default value which was causing this issue for me. If you think, there should be the default value for this state, I can send a PR to fix it.

**Comment by osdnk** [comment]
I will happily merge it
