### ISSUE TITLE
Buggy behaviour when sheet has greater height than content

### ISSUE THREAD

**Issue by bdrobinson** [osdnk/react-native-reanimated-bottom-sheet#80]
Thanks for this library, it's great!

The content of my sheet is dynamic so I can't specify its height up front. When the content is shorter than my snap point, I get this nasty transparent area which also cannot be dragged. So there's two things I need to fix – the colour, and for that area to become draggable.

![image](https://user-images.githubusercontent.com/6510515/63185099-00cf9980-c051-11e9-8c8f-ba5cd7573d49.png)

Is there a way around this? I've had a play in devtools and have found that I can set the background colour of [this `View`](https://github.com/osdnk/react-native-reanimated-bottom-sheet/blob/v1.0.0/src/index.tsx#L727) to fix the colour problem (but obviously that'd need to be exposed via some public API). But I can't see any way around the drag issue.

Thanks very much!

**Comment by bdrobinson** [comment]
I found a workaround. Given the largest snap point of my sheet (say, `200px`), if I set the header to have constant height (eg, `50px`) then I can give my content a `min-height: 150px`. Doesn't feel like a perfect solution but will do me for now 👍

**Comment by EricPKerr** [comment]
Similar issue to https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/72

**Comment by BrtqKr** [comment]
I think that's a sufficient solution, but if anyone finds something more effective feel free to comment or create a separate report.
