### ISSUE TITLE
Add  onOpenStart, onOpenEnd onCloseStart and onCloseEnd

### ISSUE THREAD

**Issue by rodolfovilaca** [osdnk/react-native-reanimated-bottom-sheet#81]
I have a feature proposal:
- Add API support for `onOpenStart`, `onOpenEnd`, `onCloseStart` and `onCloseEnd`.

## Problem:
I had to implement onClose event if the user clicked outside the bottom-sheet while having a background opacity changing. Because of gesture events problems in IOS  and Android(in a different way) i could not simply add a view to handle this tap to close event and another to change the opacity of the background, i had to put the view on the screen and remove the view manually.

## Solution
We could expose a `onOpenStart`, `onOpenEnd`, `onCloseStart` and `onCloseEnd` callback so we can control those use cases and others. I have seen some use cases here before: #57, #71.

I have a minimal implementation kinda "hacky" but solves the problem for myself as follows:

``` javascript
  const opacityValue = useLazyRef(() => new Animated.Value(1));
  const onOpenStartValue = useLazyRef(() => new Animated.Value(0));
  const onOpenEndValue = useLazyRef(() => new Animated.Value(0));
  const onCloseStartValue = useLazyRef(() => new Animated.Value(1));
  const onCloseEndValue = useLazyRef(() => new Animated.Value(0));

  <Animated.Code>
      {() => onChange(opacityValue, [
          cond(and(greaterOrEq(opacityValue, 0.9), neq(onCloseEndValue, 1)), [
            call([], onCloseEnd),
            set(onCloseEndValue, 1),
            set(onOpenStartValue, 0),
            set(onOpenEndValue, 0),
          ], [
            cond(and(lessOrEq(opacityValue, 0.1), neq(onOpenEndValue, 1)), [
              call([], onOpenEnd),
              set(onOpenEndValue, 1),
              set(onCloseStartValue, 0),
            ]),
          ]),
          cond(and(lessOrEq(opacityValue, 0.9), neq(onOpenStartValue, 1)), [
            call([], onOpenStart),
            set(onOpenStartValue, 1),
            set(onCloseEndValue, 0)
          ], [
            cond(and(greaterOrEq(opacityValue, 0.1), neq(onCloseStartValue, 1)), [
              call([], onCloseStart),
              set(onCloseStartValue, 1),
              set(onOpenEndValue, 0),
            ]),
          ])
        ])}
  </Animated.Code>
  <BottomSheet
      ref={ref}
      callbackNode={opacityValue}
      renderHeader={renderHeader}
      initialSnap={1}
      {...props}
    />
```
Could this be useful?

If you guys think so I would be happy to open a PR starting from this example or if anyone has a better idea I'm open to implement it.

**Comment by osdnk** [comment]
Looks amazing! I'll be so happy to see it!
