### ISSUE TITLE
Components with gesture handlers not working inside bottom sheet content

### ISSUE THREAD

**Issue by Simek** [osdnk/react-native-reanimated-bottom-sheet#87]
When you use component with gesture handlers inside bottom sheet content gesture events are not properly passed to children (even when events are based on different axis).

For example, putting `SwipeListView` as content results in no swipe ability:
https://github.com/jemise111/react-native-swipe-list-view

Am I doing something in a  wrong way or is there any workaround for that issue?

**Comment by brunocrpontes** [comment]
How you fixed it @Simek ?

**Comment by ofiron01** [comment]
@Simek please share your solution

**Comment by Simek** [comment]
@brunocrpontes  @ofiron01 Gesture interaction handling has been extended and now `BottomSheet` offers additionally two gesture flags based on component. When I was reporting an issue I was using old version.

Adding `enabledHeaderGestureInteraction: true` and `enabledContentGestureInteraction: false` fixed  that issue for me.

**Comment by ofiron01** [comment]
Thank you @Simek , that did the trick
