### ISSUE TITLE
Please update NPM

### ISSUE THREAD

**Issue by Under-Warz** [osdnk/react-native-reanimated-bottom-sheet#90]
The 1.0.0 version is not available on NPM, please update it ;)

**Comment by osdnk** [comment]
https://github.com/osdnk/react-native-reanimated-bottom-sheet/commit/bc295b17dbd91e1082963ac10cf0a4cf6671e6ce

**Comment by osdnk** [comment]
it's available on npm as reanimated-bottom-sheet@1.0.0-alpha.14

**Comment by Under-Warz** [comment]
thank's @osdnk
