### ISSUE TITLE
Android snapTo method doesnt work

### ISSUE THREAD

**Issue by killabeeez** [osdnk/react-native-reanimated-bottom-sheet#91]
on iOS everything is ok but on Android when i am using snapTo method app crashes however it  works fine when debugging js remotely. 

rn version 0.59.2

**Comment by rodri042** [comment]
![image](https://user-images.githubusercontent.com/1631752/64667434-34bf9400-d430-11e9-8362-d69478cd0058.png)

**Comment by vdlindenmark** [comment]
Could you provide a crash report / error log?

**Comment by imdanielpiva** [comment]
I'm having the exact same behaviour! On iOS it seems to work nice, but on Android it only works in Remote Debugging mode.

@killabeeez can you give more information about de environment you're running the app on?

```json
"reanimated-bottom-sheet": "^1.0.0-alpha.15"
```

```
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Memory: 77.25 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 27, 28
      Build Tools: 27.0.3, 28.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.2
```

**Comment by imdanielpiva** [comment]
> Could you provide a crash report / error log?

I'll try get a log over Device Manager.

**Comment by imdanielpiva** [comment]
@vdlindenmark the only Log I could get over Android Studio Log Cat was the:

`E/SDM: HWCDisplay::GetHWCLayer: [0] GetLayer(59059) failed: no such layer`, it logged it every time I clicked on the touchable that calls `snapTo`, after a few times the app crashes.

I'm running on physical device, Motorola Moto G7 Power Android 9

![Screen Shot 2019-11-05 at 10 04 09](https://user-images.githubusercontent.com/26178791/68210360-1ac7ab00-ffb4-11e9-89b3-c94d784fadf2.png)

**Comment by kubilaykiymaci** [comment]
Hi @imdanielpiva ,

Have you ever tried to add  **"import "react-native-gesture-handler"** to **index.js** or **main.js** of your app?

**Comment by imdanielpiva** [comment]
Hi, @kubilaykiymaci, I did not try it. What's the trick behind this?

**Comment by kubilaykiymaci** [comment]
i think this issue might be about "onGestureHandlerStateChange" event. [#320](https://github.com/kmagiera/react-native-gesture-handler/issues/320)

i saw [this issue](https://github.com/kmagiera/react-native-gesture-handler/issues/320) and i read [that comment](https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-443815828) before.  When i tried that, my snapping issue was solved.  @killabeeez @imdanielpiva

**Comment by CapitanRedBeard** [comment]
> Hi @imdanielpiva ,
> 
> Have you ever tried to add **"import "react-native-gesture-handler"** to **index.js** or **main.js** of your app?

This didn't work for me. Also tried to downgrade `react-native-gesture-handler` to 1.0.9 as suggested in those other threads.

My apps behavior is it works fine on iOS, but on Android calling the `snapTo` method results in a no-op, not a crash.

`"reanimated-bottom-sheet": "^1.0.0-alpha.15"`
```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 73.01 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
```

Does anyone have a workaround for not using snapTo but essentially getting the same behavior?

**Comment by killabeeez** [comment]
on RN 0.60+ it is working fine 
the only problem is that in order to have working touchable components inside of the bottom sheet, you will need to import touchable from react-native-gesture-handler for android and from react-native for iOS

**Comment by CapitanRedBeard** [comment]
I'll extend @killabeeez comment about importing touchable to those in need

If you are using Touchable*, ScrollView, or a PanResponder within the bottom sheet you may need to rewrite it so you're importing the Touchable*/ScrollView from react-native-gesture-handler and rewrite your PanResponder as a PanGestureHandler in order for the bottom sheet (which is using react-native-gesture-handler) knows when to relinquish and take control.

**Comment by imdanielpiva** [comment]
That's for sure, @CapitanRedBeard, I kind had this `react-native-gesture-handler` compatibility issue, described with more detailed info here https://github.com/nysamnang/react-native-raw-bottom-sheet/issues/37#issuecomment-550505993.
