### ISSUE TITLE
How to deal with tab bar

### ISSUE THREAD

**Issue by FrankFundel** [osdnk/react-native-reanimated-bottom-sheet#97]
Hey,
I want to implement a player bar in my custom tab bar like apple music or spotify does. 
For TabNavigator I have:
```
const TabNavigator = createBottomTabNavigator({
  HomeStack,
  LibraryStack,
},
{
  initialRouteName: 'HomeStack',
  tabBarComponent: props => <CustomTabBar {...props} />,
  tabBarOptions: {
    showLabel: false,
  }
});
```

And for my custom TabBar I wanted something like that:
```
import React from 'react';
import { BottomTabBar } from 'react-navigation';
import BottomSheet from 'reanimated-bottom-sheet'

const CustomTabBar = props => {
  return (
    <React.Fragment>
       <BottomSheet
         snapPoints = {[450, 300, 0]}
         renderContent = {this.renderInner}
         renderHeader = {this.renderHeader}
       />
      <BottomTabBar {...props} />
    </React.Fragment>
  );
};

export default CustomTabBar;
```
Problem is: the BottomSheet is behind the TabBar and blocks touches on the tabbar, so I cannot switch between tabs anymore. How to deal with this problem?

Kind Regards

**Comment by stand1715** [comment]
Wrap the BottomTabBar with <View style={{zIndex: 110}}> // more than ~100

**Comment by FrankFundel** [comment]
Oh I tried that before but with zIndex of 100, with 110 it works, thanks

**Comment by abury** [comment]
@stand1715 legend! That did the trick
